services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bact-frontend-http.rule=Host(`bact.eunaapps.com`)"
      - "traefik.http.services.bact-frontend-http.loadbalancer.server.port=80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
