services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    labels:
      - "coolify.fqdn=https://bact.eunaapps.com"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
