services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - COOLIFY_FQDN=https://bact.eunaapps.com
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
